### ISSUE TITLE
log4js-syslog-appender@0.3.1

### ISSUE THREAD

**Issue by bmict** [balemessenger/bale-bot-nodejs#8]
<div dir="rtl">
با سلام
کتابخانه log4js-syslog-appender@0.3.1 به یک بسته به نام unix-dgram@0.2.3 نیاز دارد که در سیستم‌های ویندوزی مشکل ایجاد می‌کند و نمی‌تواند نصب شود.
</div>

```bash
> unix-dgram@0.2.3 install I:\prj\node_modules\unix-dgram
> node-gyp rebuild


I:\projects\node_modules\unix-dgram>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd I:\prj\node_modules\unix-dgram
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```
<div dir="rtl">
مشکل با نصب python 2.7 و ... نیز رفع نمی‌شود زیرا کتابخانه مخصوص سیستم‌های لینوکسی است.
</div>

**Comment by masoodbayati** [comment]
سلام نصب نشدن این کتابخانه مشکلی در روند کلی کتابخانه اصلی ایجاد نمیکند 
البته که مشکل در نسخه های بعدی حل خواهد شد
